server:
  port: 8080
spring:
  task:
    scheduling:
      pool:
        size: 10
      thread-name-prefix: Scheduled-
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 50
      minimum-idle: 5
      pool-name: HikariPool
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://101.132.113.82:3306/MomentumX?createDatabaseIfNotExist=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    #    url: jdbc:mysql://localhost:3306/MomentumX?createDatabaseIfNotExist=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: root
    password: YQSaGPzeRRCvDx2mOHVMOw
  #    password: 123456
  kafka:
    bootstrap-servers: 101.132.113.82:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

mybatis-plus:
  configuration:
    cache-enabled: true
    default-executor-type: reuse
    default-statement-timeout: 25000
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
  mapper-locations: classpath:/mapper/*Mapper.xml
